[package]
name = "sns-archive"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
directories = "4.0"
fs_extra = "1.2"
futures = "0.3"
home-dir = "0.1"
itertools = "0.10"
sanitize-filename = "0.4"
tempfile = "3.3"
url = "2.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.clap]
version = "3.2"
features = ["derive"]

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["std"]
# default-features = false

[dependencies.lazy_static]
version = "1.4"
default-features = false

[dependencies.regex]
version = "1.5"
default-features = false
features = ["std"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls", "json", "stream"]

[dependencies.serde]
version = "1.0"
default-features = false
features = ["derive"]

[dependencies.serde_json]
version = "1.0"
default-features = false

[dependencies.tokio]
version = "1.19"
features = ["macros", "io-util", "io-std", "sync", "time", "rt-multi-thread", "fs"]

[dependencies.toml]
version = "0.5"
default-features = false
