name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build-upload-bins:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
            runner: windows-latest
            target: x86_64-pc-windows-msvc
          - os: linux
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            apt: libglib2.0-dev libgtk-3-dev
    runs-on: ${{ matrix.runner }}
    steps:
      - if: ${{ matrix.apt }}
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install ${{ matrix.apt }}
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: sns-archive,naver-blog-cli,naver-blog-gui
          target: ${{ matrix.target }}
          archive: ${{ github.event.repository.name }}-${{ matrix.os }}-${{ github.ref_name }}
          include: LICENSE
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
